### ISSUE TITLE
国际服 api | OS servers api

### ISSUE THREAD

**Issue by earthjasonlin** [earthjasonlin/zzz-signal-search-export#1]
由于本人不玩国际服，故无国际服的抽卡记录api，希望有热心绳匠能提供一下，谢谢

I don't play on OS servers. Therefore, I can't get the API samples for them. Hope someone can help me with it, tysm

如果您愿意帮忙，请将您的抽卡记录链接、`C:\Users\你的用户名\AppData\LocalLow\Cognosphere\Zenless Zone Zero\Player.log`、`游戏安装目录\ZenlessZoneZero_Data\webCaches\数字最大的文件夹`打包发给我的邮箱 earthjasonlin@126.com

If you would like to help, please send your Gacha Link, `C:\Users\Your username\AppData\LocalLow\Cognosphere\Zenless Zone Zero\Player.log`、`Game path\ZenlessZoneZero_Data\webCaches\folder with largest number`to my email earthjasonlin@126.com with a zip file

目前问题：我们已经知道`public-operation-nap-sg.hoyoverse.com`是其中一个服务器，但是不同于以往的`api-os`之类的，这次的域名使用了`sg`这个特殊的区域，所以有可能不同的游戏服用的不同的api服务器，所以我们需要更多的数据来验证
目前已知：`Asia => prod_gf_jp => public-operation-nap-sg`, `Europe => prod_gf_eu => public-operation-nap-sg`, `America => prod_gf_us => public-operation-nap-sg`, `TW,HK,MO => prod_gf_sg => public-operation-nap-sg`

Current Issue: We already know that `public-operation-nap-sg.hoyoverse.com` is one of the servers. However, unlike previous instances such as `api-os`, this time the domain uses the specific `sg` region. Therefore, it is possible that different game servers use different API servers. We need more data to verify this.
Current Information: `Asia => prod_gf_jp => public-operation-nap-sg`, `Europe => prod_gf_eu => public-operation-nap-sg`, `America => prod_gf_us => public-operation-nap-sg`, `TW,HK,MO => prod_gf_sg => public-operation-nap-sg`

**Comment by ezakOxO** [comment]
還需要嗎 ?

**Comment by earthjasonlin** [comment]
***@***.***
    	Get Outlook for iOS
    
  

 From: ***@***.*** ***@***.***> on behalf of ezakOxO ***@***.***>Sent: Sunday, July 21, 2024 10:49 AMTo: earthjasonlin/zzz-signal-search-export ***@***.***>Cc: Zichao Lin ***@***.***>; Author ***@***.***>Subject: Re: [earthjasonlin/zzz-signal-search-export] 国际服api (Issue #1) 
還需要嗎 ?

**Comment by earthjasonlin** [comment]
需要，谢谢，请发到我邮箱earthjasonlin@163.com

**Comment by earthjasonlin** [comment]
需要 谢谢 请把记录链接发到我的邮箱 earthjasonlin@163.com

**Comment by ezakOxO** [comment]
發了

**Comment by earthjasonlin** [comment]
每个打到开抽卡只需要20分钟，自己打完了（乐

**Comment by ezakOxO** [comment]
啊 好的
我才剛到家 哈哈

Zichao Lin ***@***.***>於 2024年7月25日 週四，21:08寫道：
