### ISSUE TITLE
点加载数据，但显示未找到URL

### ISSUE THREAD

**Issue by kira10032** [earthjasonlin/zzz-signal-search-export#2]
我的是国服，但点加载数据，显示未找到URL，我也有biuuu大的其他导出工具，也是打开抽卡记录往后翻几页，再点加载或者更新数据....

**Comment by earthjasonlin** [comment]
因为我不玩pc端所以这个没测试过，能麻烦你确认一下`C:\Users\你的用户名\AppData\LocalLow\miHoYo\绝区零\Player.log`存不存在，如果存在麻烦发我邮箱[earthjasonlin@163.com](mailto:earthjasonlin@163.com)谢谢

**Comment by awefhio** [comment]
![image](https://github.com/user-attachments/assets/bf0ecc8e-8a33-4a64-80a1-caa297796ef3)
欧服，未找到url，想请问一下提供那些文件会有帮助

**Comment by earthjasonlin** [comment]
> ![image](https://private-user-images.githubusercontent.com/170895375/352778932-bf0ecc8e-8a33-4a64-80a1-caa297796ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjM4OTAsIm5iZiI6MTcyMjEyMzU5MCwicGF0aCI6Ii8xNzA4OTUzNzUvMzUyNzc4OTMyLWJmMGVjYzhlLThhMzMtNGE2NC04MGExLWNhYTI5Nzc5NmVmMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QyMzM5NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2U2NDViNjY1NzdmMzFjMDQzMmEzYmMzNGVhOTJjOTQwZTk2ZTAxMGM1ZmJjYmQxN2MwMTE5MDU4NDZlMWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_jaH1mQ3yYlWwVQpHfafHVDB5RqEm_liWnUmeMty7I) 欧服，未找到url，想请问一下提供那些文件会有帮助

`C:\Users\你的用户名\AppData\LocalLow\Cognosphere\Zenless Zone Zero\Player.log`、`游戏安装目录\ZenlessZoneZero_Data\webCaches\数字最大的文件夹`打包发给我的邮箱

**Comment by awefhio** [comment]
已发，ZenlessZoneZero文件夹不在Cognosphere而是在miHoYo下面，不排除跟这个有关，谢谢大佬

**Comment by earthjasonlin** [comment]
> 已发，ZenlessZoneZero文件夹不在Cognosphere而是在miHoYo下面，不排除跟这个有关，谢谢大佬

没有空格吗

**Comment by awefhio** [comment]
![image](https://github.com/user-attachments/assets/c0f59b59-ab98-47de-b7a4-c3135b075c4a)

没有空格，路径是这样

C:\Users\用户名\AppData\LocalLow\miHoYo\ZenlessZoneZero

**Comment by earthjasonlin** [comment]
> ![image](https://private-user-images.githubusercontent.com/170895375/352804396-c0f59b59-ab98-47de-b7a4-c3135b075c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzkyNjksIm5iZiI6MTcyMjIzODk2OSwicGF0aCI6Ii8xNzA4OTUzNzUvMzUyODA0Mzk2LWMwZjU5YjU5LWFiOTgtNDdkZS1iN2E0LWMzMTM1YjA3NWM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNzQyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTYwYzkzNjNlMjIzMTdhYjUxZDI0MTEwMzI0YTQwN2ZkZTA3NTcxYTQ5NDYyZjlmNDdmYTMzMDk3ZDRkOWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GNRQfV9LaXZb_Lv2geoqUaWjqH_evFrQtexfdVjGfYw)
> 
> 没有空格，路径是这样
> 
> C:\Users\用户名\AppData\LocalLow\miHoYo\ZenlessZoneZero

1.1.4
