### ISSUE TITLE
关于导出excel的问题

### ISSUE THREAD

**Issue by Reopeko** [earthjasonlin/zzz-signal-search-export#3]
1、对应的A级一行颜色显示灰色（应为紫色）
2、对应的S级一行颜色显示紫色（应为橙色或者橘色）
3、保底内次数计算，出了S级后未重头归0计算
4、星级分类应各自往上提一级。？

**Comment by earthjasonlin** [comment]
https://github.com/earthjasonlin/zzz-signal-search-export/releases/tag/v1.0.7
