### ISSUE TITLE
国际服时区 | OS Servers' Time Zone

### ISSUE THREAD

**Issue by earthjasonlin** [earthjasonlin/zzz-signal-search-export#4]
我们需要我们知道服务器的时区，但是API不直接返回时区给我们，所以我们需要手动定义每个服务器的时区；如果有朋友愿意帮忙完善这个程序，帮忙完成一个小小的测试的话，请联系我的邮箱 earthjasonlin@126.com

Now requires us to know the server's time zone. However, hoyo's API doesn't tell us about it, so we have to get the time zone for each server maually. If you want to make this program better are kind enough to help me with some simple tests, please contact me at earthjasonlin@126.com

目前已知：国服：`prod_gf_cn` UTC+8 亚服：`prod_gf_jp` UTC+8 欧服：`prod_gf_eu` UTC+1 美服：`prod_gf_us` UTC-5 港澳台服：`prod_gf_sg` UTC+8

Current Info.: CN: `prod_gf_cn` UTC+8 Asia: `prod_gf_jp` UTC+8 Europe：`prod_gf_eu` UTC+1 America：`prod_gf_us` UTC-5 TW,HK,MO：`prod_gf_sg` UTC+8

**Comment by JamesRagnarok** [comment]
我玩亞洲服，要如何幫你？

**Comment by earthjasonlin** [comment]
> 我玩亞洲服，要如何幫你？

请你进行一次抽卡，然后将抽卡记录链接、你这次抽卡的UTC时间、卡池是哪一个、抽卡的结果邮箱发给我。

**Comment by JamesRagnarok** [comment]
抽卡紀錄連結可以用這個網站的方式取得嗎？還是要用別的方法？
https://zzz.rng.moe/en/tracker/import

**Comment by earthjasonlin** [comment]
> 抽卡紀錄連結可以用這個網站的方式取得嗎？還是要用別的方法？ https://zzz.rng.moe/en/tracker/import

可以的
